import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@components/navbar'
import Footer from '@components/Footer'
import Provider from '@components/Provider'
import { Toaster } from "@components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ashmeet Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}
